# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Try < Formula
  desc "Fresh directories for every vibe - ephemeral workspace manager"
  homepage "https://github.com/amulcse/try"
  version "1.8.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/amulcse/try/releases/download/v1.8.1/try_darwin_amd64.tar.gz"
      sha256 "29e2e69417d183c5f68c51b2e43a98d28abcf4e29ea6302b78eb0831313f80da"

      def install
        bin.install "try"
      end
    end
    on_arm do
      url "https://github.com/amulcse/try/releases/download/v1.8.1/try_darwin_arm64.tar.gz"
      sha256 "9c4b7f5fba67b536e40e128922ecbe335c4d72f22ab6b42fe164f963a0937ba2"

      def install
        bin.install "try"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/amulcse/try/releases/download/v1.8.1/try_linux_amd64.tar.gz"
        sha256 "b40d91151d923b0ac7289070ab30cad0e02193566adf4ffed8b7177c7bbab697"

        def install
          bin.install "try"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/amulcse/try/releases/download/v1.8.1/try_linux_arm64.tar.gz"
        sha256 "a18fc2de91f0b133307ec9be40388106f802b48b49d6cc22ca9f79e4f126ecf9"

        def install
          bin.install "try"
        end
      end
    end
  end

  def caveats
    <<~EOS
      To complete installation, add this to your shell config:

      For bash/zsh (~/.bashrc or ~/.zshrc):
        eval "$(try init)"

      For fish (~/.config/fish/config.fish):
        eval (try init | string collect)

      Then restart your terminal.
    EOS
  end

  test do
    system "#{bin}/try", "--version"
  end
end
