# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Try < Formula
  desc "Fresh directories for every vibe - ephemeral workspace manager"
  homepage "https://github.com/amulcse/try"
  version "1.8.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/amulcse/try/releases/download/v1.8.0/try_darwin_amd64.tar.gz"
      sha256 "07909ace74e693028c455c8e9d538740fe5516129d149004036e9ab97964dbe9"

      def install
        bin.install "try"
      end
    end
    on_arm do
      url "https://github.com/amulcse/try/releases/download/v1.8.0/try_darwin_arm64.tar.gz"
      sha256 "b3926d214af7559d104d943f43f3fb052510ab3d7128f155da918b5874ae2132"

      def install
        bin.install "try"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/amulcse/try/releases/download/v1.8.0/try_linux_amd64.tar.gz"
        sha256 "c62b8870420429a816c703001b396ea55ef4265550efc742676a0c6692df3550"

        def install
          bin.install "try"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/amulcse/try/releases/download/v1.8.0/try_linux_arm64.tar.gz"
        sha256 "ed21206f589986449273a15e5440b690a018488da3d8c72f81d945d2c7e7cea1"

        def install
          bin.install "try"
        end
      end
    end
  end

  def caveats
    <<~EOS
      To complete installation, add this to your shell config:

      For bash/zsh (~/.bashrc or ~/.zshrc):
        eval "$(try init)"

      For fish (~/.config/fish/config.fish):
        eval (try init | string collect)

      Then restart your terminal.
    EOS
  end

  test do
    system "#{bin}/try", "--version"
  end
end
