# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Try < Formula
  desc "Fresh directories for every vibe - ephemeral workspace manager"
  homepage "https://github.com/amulcse/try"
  version "1.7.4"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/amulcse/try/releases/download/v1.7.4/try_darwin_amd64.tar.gz"
      sha256 "22a23cabb44795e12f959be40f4f51394c12a7277f90f999c98f4310bb9c7355"

      def install
        bin.install "try"
      end
    end
    on_arm do
      url "https://github.com/amulcse/try/releases/download/v1.7.4/try_darwin_arm64.tar.gz"
      sha256 "4ed1990ca679897871296bb640cde587f2a9bbde6a6546b3dea8aeb20349f23c"

      def install
        bin.install "try"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/amulcse/try/releases/download/v1.7.4/try_linux_amd64.tar.gz"
        sha256 "1647d09a93176a96d201786446c70f904abd2bd353fabcea2facb79184cb81fa"

        def install
          bin.install "try"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/amulcse/try/releases/download/v1.7.4/try_linux_arm64.tar.gz"
        sha256 "df6886ca6a49da9b371c076d6a750605d0c210abd6f2ba19e545a7ef1082ceae"

        def install
          bin.install "try"
        end
      end
    end
  end

  def caveats
    <<~EOS
      To complete installation, add this to your shell config:

      For bash/zsh (~/.bashrc or ~/.zshrc):
        eval "$(try init)"

      For fish (~/.config/fish/config.fish):
        eval (try init | string collect)

      Then restart your terminal.
    EOS
  end

  test do
    system "#{bin}/try", "--version"
  end
end
